INSERT INTO tutors (id,education,bio,rate_per_hour) VALUES
(1420,'McGill University ','McGill Fourth year Mathematics major with a history of tutoring and a passion for teaching. Let me know what you need help with ! I am able to teach anything up to calculus 4 and discrete structures',30),
(1421,'Self-Taught','Entrepreneur passionate about technology, high-tech combat suits and extra-terrestrial life. Genius level intelect. I also bake cookies.',99),
(1422,'Ryerson University','Math teacher at the High School level, lots of experience teaching kids age 11-17 in algebra, geometry and calculus',45),
(1423,'University of Toronto','3rd year Honors Philosophy student. My course load is focussed on existentialism and modern european Philosophy. TA for PHIL 375',45),
(1424,'Aristotle School of Metaphysics','Emperor of Macedon, Grece and Anatolia. Conquered most of the known world by the age of 20. Learnt lots about Philosophy from Aristotle and others.',85),
(1425,'Platonic School of Athens','Student of Plato, Mentor to Alexander. Life long scholar in Philosophy, Poetry and Mathematics. Will travel the world to teach. Occasionnally very wrong about physics (hire at your own risk) ',60);

INSERT INTO tutors (id,education,bio,rate_per_hour) VALUES (793,'McGill University ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer',42),(797,' University of Toronto ','Lorem ipsum dolor sit amet, consectetuer adipiscing',26),(801,' Harvard ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna',20),(805,' Concordia University ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed',35),(809,' Lighthouse Univerity ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.',30),(813,' Hogwarts but for code','Lorem ipsum dolor sit amet, consectetuer adipiscing',50),(817,'McGill University ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.',20),(821,' University of Toronto ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam',19),(825,' Harvard ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam',50),(829,' Concordia University ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu',26);
INSERT INTO tutors (id,education,bio,rate_per_hour) VALUES (833,' Lighthouse Univerity ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.',21),(837,' Hogwarts but for code','Lorem ipsum dolor sit amet, consectetuer adipiscing',29),(841,'McGill University ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing',39),(845,' University of Toronto ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et',38),(849,' Harvard ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu',43),(853,' Concordia University ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna',47),(857,' Lighthouse Univerity ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et',46),(861,' Hogwarts but for code','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam',33),(865,'McGill University ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec',16),(869,' University of Toronto ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',19);
INSERT INTO tutors (id,education,bio,rate_per_hour) VALUES (873,' Harvard ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam',28),(877,' Concordia University ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et',18),(881,' Lighthouse Univerity ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.',45),(885,' Hogwarts but for code','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec',28),(889,'McGill University ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut',37),(893,' University of Toronto ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna',35),(897,' Harvard ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed',39),(901,' Concordia University ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna',33),(905,' Lighthouse Univerity ','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing',29),(909,' Hogwarts but for code','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et',44);
